# Project: Exploratory Data Analysis
Perform exploratory data analysis (EDA) to gain insights from a data lake.

## Instructions

In `dbfs:/mnt/training/crime-data-2016`, there are a number of Parquet files containing 2016 crime data from seven United States cities:

* New York
* Los Angeles
* Chicago
* Philadelphia
* Dallas
* Boston

The data is cleaned up a little, but has not been normalized. Each city reports crime data slightly differently, so
examine the data for each city to determine how to query it properly.

Your job is to use some of this data to gain insights about certain kinds of crimes.

### Getting Started

Run the following cell to configure our "classroom."

In [3]:
%run ../Includes/Classroom-Setup

## Step 1

Start by creating DataFrames for Los Angeles, Philadelphia, and Dallas data.

Use `spark.read.parquet` to create named DataFrames for the files you choose. 

To read in the parquet file, use `crimeDataNewYorkDF = spark.read.parquet("/mnt/training/crime-data-2016/Crime-Data-New-York-2016.parquet")`


Use the following view names:

| City          | DataFrame Name            | Path to DBFS file
| ------------- | ------------------------- | -----------------
| Los Angeles   | `crimeDataLosAngelesDF`   | `dbfs:/mnt/training/crime-data-2016/Crime-Data-Los-Angeles-2016.parquet`
| Philadelphia  | `crimeDataPhiladelphiaDF` | `dbfs:/mnt/training/crime-data-2016/Crime-Data-Philadelphia-2016.parquet`
| Dallas        | `crimeDataDallasDF`       | `dbfs:/mnt/training/crime-data-2016/Crime-Data-Dallas-2016.parquet`

#### Los Angeles

In [6]:
# TODO

crimeDataLosAngelesDF = # FILL_IN

In [7]:
# TEST - Run this cell to test your solution.

rowsLosAngeles  = crimeDataLosAngelesDF.count()
dbTest("DF-L7-crimeDataLA-count", rowsLosAngeles, 217945)

print("Tests passed!")

#### Philadelphia

In [9]:
# TODO

crimeDataPhiladelphiaDF = # FILL_IN

In [10]:
# TEST - Run this cell to test your solution.

rowsPhiladelphia  = crimeDataPhiladelphiaDF.count()
dbTest("DF-L7-crimeDataPA-count", rowsPhiladelphia, 168664)

print("Tests passed!")

#### Dallas

In [12]:
# TODO

crimeDataDallasDF = # FILL_IN

In [13]:
# TEST - Run this cell to test your solution.

rowsDallas  = crimeDataDallasDF.count()
dbTest("DF-L7-crimeDataDAL-count", 99642, rowsDallas)

print("Tests passed!")

-sandbox
## Step 2

For each table, examine the data to figure out how to extract _robbery_ statistics.

<img alt="Side Note" title="Side Note" style="vertical-align: text-bottom; position: relative; height:1.75em; top:0.05em; transform:rotate(15deg)" src="https://files.training.databricks.com/static/images/icon-note.webp"/> Each city uses different values to indicate robbery. Commonly used terminology is "larceny", "burglary" or "robbery."  These challenges are common in Data Lakes.  Restrict yourself to only robberies.

Explore the data for the three cities until you understand how each city records robbery information. If you don't want to worry about upper- or lower-case, 
remember to use the DataFrame `lower()` method to converts column values to lowercase.

Create a DataFrame containing only the robbery-related rows, as shown in the table below.

<img alt="Hint" title="Hint" style="vertical-align: text-bottom; position: relative; height:1.75em; top:0.3em" src="https://files.training.databricks.com/static/images/icon-light-bulb.svg"/>&nbsp;**Hint:** For each table, focus your efforts on the column listed below.

Focus on the following columns for each table:

| DataFrame Name            | Robbery DataFrame Name  | Column
| ------------------------- | ----------------------- | -------------------------------
| `crimeDataLosAngelesDF`   | `robberyLosAngelesDF`   | `crimeCodeDescription`
| `crimeDataPhiladelphiaDF` | `robberyPhiladelphiaDF` | `ucr_general_description`
| `crimeDataDallasDF`       | `robberyDallasDF`       | `typeOfIncident`

#### Los Angeles

In [16]:
# TODO
from pyspark.sql.functions import col, lower
robberyLosAngelesDF = # FILL_IN

In [17]:
# TEST - Run this cell to test your solution.

totalLosAngeles  = robberyLosAngelesDF.count()
dbTest("DF-L7-robberyDataLA-count", 9048, totalLosAngeles)

print("Tests passed!")

#### Philadelphia

In [19]:
# TODO

robberyPhiladelphiaDF  = # FILL_IN

In [20]:
# TEST - Run this cell to test your solution.

totalPhiladelphia  = robberyPhiladelphiaDF.count()
dbTest("DF-L7-robberyDataPA-count", 6149, totalPhiladelphia)

print("Tests passed!")

#### Dallas

In [22]:
# TODO

robberyDallasDF = # FILL_IN

In [23]:
# TEST - Run this cell to test your solution.

totalDallas = robberyDallasDF.count()
dbTest("DF-L7-robberyDataDAL-count", 6824, totalDallas)

print("Tests passed!")

-sandbox
## Step 3

Now that you have DataFrames of only the robberies in each city, create DataFrames for each city summarizing the number of robberies in each month.

Your DataFrames must contain two columns:
* `month`: The month number (e.g., 1 for January, 2 for February, etc.).
* `robberies`: The total number of robberies in the month.

Use the following DataFrame names and date columns:


| City          | DataFrame Name     | Date Column 
| ------------- | ------------- | -------------
| Los Angeles   | `robberiesByMonthLosAngelesDF` | `timeOccurred`
| Philadelphia  | `robberiesByMonthPhiladelphiaDF` | `dispatch_date_time`
| Dallas        | `robberiesByMonthDallasDF` | `startingDateTime`

<img alt="Side Note" title="Side Note" style="vertical-align: text-bottom; position: relative; height:1.75em; top:0.05em; transform:rotate(15deg)" src="https://files.training.databricks.com/static/images/icon-note.webp"/> For each city, figure out which column contains the date of the incident. Then, extract the month from that date.

#### Los Angeles

In [26]:
# TODO

from pyspark.sql.functions import month, col
robberiesByMonthLosAngelesDF = # FILL_IN

In [27]:
# TEST - Run this cell to test your solution.
from pyspark.sql import Row
la = list(robberiesByMonthLosAngelesDF.collect())

dbTest("DF-L7-robberyByMonthLA-counts", [Row(month=1, robberies=719), Row(month=2, robberies=675), Row(month=3, robberies=709), Row(month=4, robberies=713), Row(month=5, robberies=790), Row(month=6, robberies=698), Row(month=7, robberies=826), Row(month=8, robberies=765), Row(month=9, robberies=722), Row(month=10, robberies=814), Row(month=11, robberies=764), Row(month=12, robberies=853)], la)

print("Tests passed!")

#### Philadelphia

In [29]:
# TODO

robberiesByMonthPhiladelphiaDF = # FILL_IN

In [30]:
# TEST - Run this cell to test your solution.
# convert to list so that we get deep compare (Array would be a shallow compare)
philadelphia  = list(robberiesByMonthPhiladelphiaDF.collect())

dbTest("DF-L7-robberyByMonthPA-counts", [Row(month=1, robberies=520), Row(month=2, robberies=416), Row(month=3, robberies=432), Row(month=4, robberies=466), Row(month=5, robberies=533), Row(month=6, robberies=509), Row(month=7, robberies=537), Row(month=8, robberies=561), Row(month=9, robberies=514), Row(month=10, robberies=572), Row(month=11, robberies=545), Row(month=12, robberies=544)], philadelphia )

print("Tests passed!")

#### Dallas

In [32]:
# TODO

robberiesByMonthDallasDF = # FILL_IN

In [33]:
# TEST - Run this cell to test your solution.

dallas  = list(robberiesByMonthDallasDF.collect())
dbTest("DF-L7-robberyByMonthDAL-counts", [Row(month=1, robberies=743), Row(month=2, robberies=435), Row(month=3, robberies=412), Row(month=4, robberies=594), Row(month=5, robberies=615), Row(month=6, robberies=495), Row(month=7, robberies=535), Row(month=8, robberies=627), Row(month=9, robberies=512), Row(month=10, robberies=603), Row(month=11, robberies=589), Row(month=12, robberies=664)], dallas)

print("Tests passed!")

-sandbox

## Step 4

Plot the robberies per month for each of the three cities, producing a plot similar to the following:

<img src="https://files.training.databricks.com/images/eLearning/robberies-by-month.png" style="max-width: 700px; border: 1px solid #aaaaaa; border-radius: 10px 10px 10px 10px"/>

When you first run the cell, you'll get an HTML table as the result. To configure the plot:

1. Click the graph button.
2. If the plot doesn't look correct, click the **Plot Options** button.
3. Configure the plot similar to the following example.

<img src="https://files.training.databricks.com/images/eLearning/capstone-plot-1.png" style="width: 440px; margin: 10px; border: 1px solid #aaaaaa; border-radius: 10px 10px 10px 10px"/>
<img src="https://files.training.databricks.com/images/eLearning/capstone-plot-2.png" style="width: 268px; margin: 10px; border: 1px solid #aaaaaa; border-radius: 10px 10px 10px 10px"/>
<img src="https://files.training.databricks.com/images/eLearning/capstone-plot-3.png" style="width: 362px; margin: 10px; border: 1px solid #aaaaaa; border-radius: 10px 10px 10px 10px"/>

#### Los Angeles

In [36]:
# TODO

FILL_IN

#### Philadelphia

In [38]:
# TODO

FILL_IN

#### Dallas

In [40]:
# TODO

FILL_IN

-sandbox
## Step 5

Create another DataFrame called `combinedRobberiesByMonthDF`, that combines all three robberies-per-month views into one.
In creating this view, add a new column called `city`, that identifies the city associated with each row.
The final view will have the following columns:

* `city`: The name of the city associated with the row. (Use the strings "Los Angeles", "Philadelphia", and "Dallas".)
* `month`: The month number associated with the row.
* `robbery`: The number of robbery in that month (for that city).

<img alt="Hint" title="Hint" style="vertical-align: text-bottom; position: relative; height:1.75em; top:0.3em" src="https://files.training.databricks.com/static/images/icon-light-bulb.svg"/>&nbsp;**Hint:** You may want to apply the `union()` method in this example to combine the three datasets.

<img alt="Hint" title="Hint" style="vertical-align: text-bottom; position: relative; height:1.75em; top:0.3em" src="https://files.training.databricks.com/static/images/icon-light-bulb.svg"/>&nbsp;**Hint:** It's easy to add new columns in DataFrames. For example, add a new column called `newColumn` to `originalDF` use `withColumn()` method as follows:

```originalDF.withColumn("newColumn")```

In [42]:
# TODO

from pyspark.sql.functions import lit

combinedRobberiesByMonthDF = # FILL_IN

In [43]:
# TEST - Run this cell to test your solution.

results = [ (r.city, r.month, r.robberies) for r in combinedRobberiesByMonthDF.collect() ]
expectedResults =  [ 
(u'Los Angeles', 1, 719), 
(u'Los Angeles', 2, 675), 
(u'Los Angeles', 3, 709), 
(u'Los Angeles', 4, 713),   
(u'Los Angeles', 5, 790), 
(u'Los Angeles', 6, 698), 
(u'Los Angeles', 7, 826), 
(u'Los Angeles', 8, 765), 
(u'Los Angeles', 9, 722), 
(u'Los Angeles', 10, 814), 
(u'Los Angeles', 11, 764), 
(u'Los Angeles', 12, 853), 
(u'Philadelphia', 1, 520), 
(u'Philadelphia', 2, 416), 
(u'Philadelphia', 3, 432), 
(u'Philadelphia', 4, 466),
(u'Philadelphia', 5, 533), 
(u'Philadelphia', 6, 509), 
(u'Philadelphia', 7, 537), 
(u'Philadelphia', 8, 561), 
(u'Philadelphia', 9, 514), 
(u'Philadelphia', 10, 572), 
(u'Philadelphia', 11, 545), 
(u'Philadelphia', 12, 544), 
(u'Dallas', 1, 743),
(u'Dallas', 2, 435), 
(u'Dallas', 3, 412), 
(u'Dallas', 4, 594), 
(u'Dallas', 5, 615), 
(u'Dallas', 6, 495), 
(u'Dallas', 7, 535), 
(u'Dallas', 8, 627), 
(u'Dallas', 9, 512), 
(u'Dallas', 10, 603), 
(u'Dallas', 11, 589), 
(u'Dallas', 12, 664)] 

dbTest("DF-L7-combinedRobberiesByMonth-counts", expectedResults, results)

print("Tests passed!")

In [44]:
combinedRobberiesByMonthDF.select("city")

-sandbox
## Step 6

Graph the contents of `combinedRobberiesByMonthDF`, producing a graph similar to the following. (The diagram below deliberately
uses different data.)

<img src="https://files.training.databricks.com/images/eLearning/combined-homicides.png" style="width: 800px; border: 1px solid #aaaaaa; border-radius: 10px 10px 10px 10px"/>

Adjust the plot options to configure the plot properly, as shown below:

<img src="https://files.training.databricks.com/images/eLearning/capstone-plot-4.png" style="width: 362px; margin: 10px; border: 1px solid #aaaaaa; border-radius: 10px 10px 10px 10px"/>

<img alt="Hint" title="Hint" style="vertical-align: text-bottom; position: relative; height:1.75em; top:0.3em" src="https://files.training.databricks.com/static/images/icon-light-bulb.svg"/>&nbsp;**Hint:** Order your results by `month`, then `city`.

In [46]:
# TODO

FILL_IN

## Step 7

While the above graph is interesting, it's flawed: it's comparing the raw numbers of robberies, not the per capita robbery rates.

The DataFrame (already created) called `cityDataDF`  contains, among other data, estimated 2016 population values for all United States cities
with populations of at least 100,000. (The data is from [Wikipedia](https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population).)

* Use the population values in that table to normalize the robberies so they represent per-capita values (total robberies divided by population).
* Save your results in a DataFrame called `robberyRatesByCityDF`.
* The robbery rate value must be stored in a new column, `robberyRate`.

Next, graph the results, as above.

In [48]:
# TODO

# rename "city" column to "cities" to avoid having two similarly named cols; also columns are case-blind
cityDataDF = spark.read.parquet("dbfs:/mnt/training/City-Data.parquet").withColumnRenamed("city", "cities")

robberyRatesByCityDF = # FILL_IN

In [49]:
# TEST - Run this cell to test your solution.
results = [ (r.city, r.month, '{:6f}'.format(r.robberyRate)) for r in robberyRatesByCityDF.orderBy("city", "month").collect() ]
expectedResults = [
  (u'Dallas',  1, '0.000564'),
  (u'Dallas',  2, '0.000330'),
  (u'Dallas',  3, '0.000313'),
  (u'Dallas',  4, '0.000451'),
  (u'Dallas',  5, '0.000467'),
  (u'Dallas',  6, '0.000376'),
  (u'Dallas',  7, '0.000406'),
  (u'Dallas',  8, '0.000476'),
  (u'Dallas',  9, '0.000388'),
  (u'Dallas', 10, '0.000458'),
  (u'Dallas', 11, '0.000447'),
  (u'Dallas', 12, '0.000504'),
  (u'Los Angeles',  1, '0.000181'),
  (u'Los Angeles',  2, '0.000170'),
  (u'Los Angeles',  3, '0.000178'),
  (u'Los Angeles',  4, '0.000179'),
  (u'Los Angeles',  5, '0.000199'),
  (u'Los Angeles',  6, '0.000176'),
  (u'Los Angeles',  7, '0.000208'),
  (u'Los Angeles',  8, '0.000192'),
  (u'Los Angeles',  9, '0.000182'),
  (u'Los Angeles', 10, '0.000205'),
  (u'Los Angeles', 11, '0.000192'),
  (u'Los Angeles', 12, '0.000215'),
  (u'Philadelphia',  1, '0.000332'),
  (u'Philadelphia',  2, '0.000265'),
  (u'Philadelphia',  3, '0.000276'),
  (u'Philadelphia',  4, '0.000297'),
  (u'Philadelphia',  5, '0.000340'),
  (u'Philadelphia',  6, '0.000325'),
  (u'Philadelphia',  7, '0.000343'),
  (u'Philadelphia',  8, '0.000358'),
  (u'Philadelphia',  9, '0.000328'),
  (u'Philadelphia', 10, '0.000365'),
  (u'Philadelphia', 11, '0.000348'),
  (u'Philadelphia', 12, '0.000347')]
dbTest("DF-L7-roberryRatesByCity-counts", expectedResults, results)

print("Tests passed!")

## References

The crime data used in this notebook comes from the following locations:

| City          | Original Data 
| ------------- | -------------
| Boston        | <a href="https://data.boston.gov/group/public-safety" target="_blank">https&#58;//data.boston.gov/group/public-safety</a>
| Chicago       | <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2" target="_blank">https&#58;//data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2</a>
| Dallas        | <a href="https://www.dallasopendata.com/Public-Safety/Police-Incidents/tbnj-w5hb/data" target="_blank">https&#58;//www.dallasopendata.com/Public-Safety/Police-Incidents/tbnj-w5hb/data</a>
| Los Angeles   | <a href="https://data.lacity.org/A-Safe-City/Crime-Data-From-2010-to-Present/y8tr-7khq" target="_blank">https&#58;//data.lacity.org/A-Safe-City/Crime-Data-From-2010-to-Present/y8tr-7khq</a>
| New Orleans   | <a href="https://data.nola.gov/Public-Safety-and-Preparedness/Electronic-Police-Report-2016/4gc2-25he/data" target="_blank">https&#58;//data.nola.gov/Public-Safety-and-Preparedness/Electronic-Police-Report-2016/4gc2-25he/data</a>
| New York      | <a href="https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i" target="_blank">https&#58;//data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i</a>
| Philadelphia  | <a href="https://www.opendataphilly.org/dataset/crime-incidents" target="_blank">https&#58;//www.opendataphilly.org/dataset/crime-incidents</a>